project:
  type: website
  output-dir: docs

website:
  title: "11rchitwood.github.io"
  description: "My Data Science Portfolio"
  site-url: https://11rchitwood.github.io
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/11rchitwood
      - icon: linkedin
        href: https://linkedin.com/in/11rchitwood/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual
